### PR TITLE
Tailwind CSS Responsive Navbar Added

### LINKED ISSUE #18: Add a simplistic header using tailwind css to navigate to pages
**Acceptance Criteria**
1. Add a simple header using tailwind 
2. Link to /minting /register_form and other pages
3. Test for smaller and bigger screens. Using the deployed url after you create the PR

### PR DESCRIPTION
**Pull request by al3sha9**

### CODE REVIEW

**Comment by al3sha9** [comment]
@hunzai sir this PR has some deployment issues but there are no conflicts

**Comment by al3sha9** [comment]
@hunzai sir should i work on the whole page responsiveness?

**Comment by hunzai** [comment]
check why the Vercel deployment is failing. It should pass

**Comment by hunzai** [comment]
make sure you
- you pushed all code
- rm node_modules 
- build locally

**Comment by hunzai** [comment]
run 
`npm run lint` to findout what is wrong with code and fix it

**Comment by al3sha9** [comment]
Sure sir

**Comment by hunzai** [comment]
@al3sha9 the deployment is still failing please check

**Comment by al3sha9** [comment]
Screenshot (1)

**Comment by al3sha9** [comment]
sir lint shows no errors, github was showing errors for the coverage files i tried pushing the code without coverage folder but still same error

**Comment by al3sha9** [comment]
branch is clear

**Comment by al3sha9** [comment]
sir, are we merging this?

**Pull request merged**
