### PR TITLE
Jest testing

### PR DESCRIPTION
**Pull request by Shan-barcha**
Initially, I forgot to create a new branch, but after that, I just created a new branch, then generated a pull request, which said nothing to be compared, so I committed some changes and added a new commit, and then the changes appeared.

### CODE REVIEW

**Comment by hunzai** [comment]
@Shan-barcha please remove test output folder coverage. Anything that is not required for the app shouldn't be committed. 

Good work!

**Comment by Shan-barcha** [comment]
sir, I added a coverage folder to git ignore but it is not ignoring what should I do?

**Comment by Shan-barcha** [comment]
sir, I added a coverage folder to git ignore but it is not ignoring what should I do?

**Comment by Shan-barcha** [comment]
@hunzai sir I added a coverage folder to git ignore but it is not ignoring, what should I do sir?
coverage folder is created automatically when I run the test.

**Comment by hunzai** [comment]
check https://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore

**Pull request merged**
